In [20]:
import functions as fn
import numpy as np

%load_ext autoreload

%autoreload 2

print(fn.create_NT(1, 3)[0])

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
[[ 0.74074074  0.44444444  0.25925926 -0.22222222]]


In [21]:
big_list=list(range(5))
my_list = [0,2,3]
print([x for x in big_list if x not in my_list])

[1, 4]


In [60]:
my_arr = np.arange(6).reshape(6,)
a1, a2, a3, a4, a5, a6 = my_arr
print(my_arr[0])

0


In [70]:
my_zeros = np.zeros(6)
print(my_zeros)
my_ones = np.ones(2)
print(my_ones)
emp = np.array([])
print(emp)
emp = np.append(emp, my_zeros)
print(emp)

[0. 0. 0. 0. 0. 0.]
[1. 1.]
[]
[0. 0. 0. 0. 0. 0.]
